# Generated by Django 3.2.3 on 2021-08-02 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='repetir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
