# Generated by Django 3.2.3 on 2021-08-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20210802_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='modo',
            field=models.BooleanField(default=True),
        ),
    ]
