# Generated by Django 3.2.3 on 2021-05-19 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_remove_dispositivo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo', to='iot.dispositivo'),
        ),
    ]
