# Generated by Django 3.2.3 on 2021-08-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20210801_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumo',
        ),
    ]
