# Generated by Django 3.2.3 on 2021-08-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_agendamento_modo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='executado',
            field=models.BooleanField(default=False),
        ),
    ]
