# Generated by Django 3.2.3 on 2021-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_agendamento_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='icon',
            field=models.CharField(default='plug.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='hardware_id',
            field=models.CharField(default='1234', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='name',
            field=models.CharField(default='Abajur', max_length=100),
        ),
    ]
