# Generated by Django 3.2.3 on 2021-08-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_agendamento_executado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='executado',
        ),
    ]
