# Generated by Django 3.2.3 on 2021-10-06 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='horario',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
